import type { Metadata } from "next";
import { Archivo } from "next/font/google";
import "./globals.css";

const font = Archivo({
  variable: "--font-archivo",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body
        className={`${font.variable} bg-gradient-to-r from-slate-950 to-slate-900 text-slate-300  antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
